mod list;
mod register;
mod show_config;
mod unregister;

use clap::Subcommand;
use tuwunel_core::Result;

use crate::admin_command_dispatch;

#[derive(Debug, Subcommand)]
#[admin_command_dispatch(handler_prefix = "appservice")]
pub(super) enum AppserviceCommand {
	/// - Register an appservice using its registration YAML
	///
	/// This command needs a YAML generated by an appservice (such as a bridge),
	/// which must be provided in a Markdown code block below the command.
	///
	/// Registering a new bridge using the ID of an existing bridge will replace
	/// the old one.
	Register,

	/// - Unregister an appservice using its ID
	///
	/// You can find the ID using the `list-appservices` command.
	Unregister {
		/// The appservice to unregister
		appservice_identifier: String,
	},

	/// - Show an appservice's config using its ID
	///
	/// You can find the ID using the `list-appservices` command.
	#[clap(alias("show"))]
	ShowConfig {
		/// The appservice to show
		appservice_identifier: String,
	},

	/// - List all the currently registered appservices
	List,
}
