# tuwunel

services:
    homeserver:
        ### If you already built the tuwunel image with 'docker build' or want to use a registry image,
        ### then you are ready to go.
        image: jevolk/tuwunel:latest
        restart: unless-stopped
        ports:
            - 443:6167
        volumes:
            - db:/var/lib/tuwunel
            #- ./tuwunel.toml:/etc/tuwunel.toml
        environment:
            TUWUNEL_SERVER_NAME: your.server.name # EDIT THIS
            TUWUNEL_DATABASE_PATH: /var/lib/tuwunel
            TUWUNEL_PORT: 6167
            TUWUNEL_MAX_REQUEST_SIZE: 20000000 # in bytes, ~20 MB
            TUWUNEL_ALLOW_REGISTRATION: 'true'
            TUWUNEL_REGISTRATION_TOKEN: 'YOUR_TOKEN' # A registration token is required when registration is allowed.
            #TUWUNEL_YES_I_AM_VERY_VERY_SURE_I_WANT_AN_OPEN_REGISTRATION_SERVER_PRONE_TO_ABUSE: 'true'
            TUWUNEL_ALLOW_FEDERATION: 'true'
            TUWUNEL_ALLOW_CHECK_FOR_UPDATES: 'true'
            TUWUNEL_TRUSTED_SERVERS: '["matrix.org"]'
            #TUWUNEL_LOG: warn,state_res=warn
            TUWUNEL_ADDRESS: 0.0.0.0
            #TUWUNEL_CONFIG: '/etc/tuwunel.toml' # Uncomment if you mapped config toml above
    #
    ### Uncomment if you want to use your own Element-Web App.
    ### Note: You need to provide a config.json for Element and you also need a second
    ###       Domain or Subdomain for the communication between Element and tuwunel
    ### Config-Docs: https://github.com/vector-im/element-web/blob/develop/docs/config.md
    # element-web:
    #     image: vectorim/element-web:latest
    #     restart: unless-stopped
    #     ports:
    #         - 8009:80
    #     volumes:
    #         - ./element_config.json:/app/config.json
    #     depends_on:
    #         - homeserver

volumes:
    db:
